// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpedGlVEiUVkw38MSWsqAKk_Wp6sZVAIs',
    appId: '1:1018275013948:android:26a72bcb6db260ab57ea39',
    messagingSenderId: '1018275013948',
    projectId: 'listly-ef975',
    storageBucket: 'listly-ef975.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1DC2u248q0f61QxDxDChEpTP_cNb6YX8',
    appId: '1:1018275013948:ios:9b983caf82ec31c457ea39',
    messagingSenderId: '1018275013948',
    projectId: 'listly-ef975',
    storageBucket: 'listly-ef975.firebasestorage.app',
    androidClientId: '1018275013948-7uhn9ittg30hv8oftubc18dj34gui5lh.apps.googleusercontent.com',
    iosClientId: '1018275013948-vlr0q57alm8hqjtdm409rvjv8eqv7ast.apps.googleusercontent.com',
    iosBundleId: 'com.hbdev.listly',
  );

}