// Mocks generated by Mockito 5.4.6 from annotations
// in listly/test/helpers/mock_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:listly/core/database/sembast/sembast_service.dart' as _i6;
import 'package:listly/features/shopping_list/domain/repositories/shopping_list_repository.dart'
    as _i7;
import 'package:listly/shared/models/shopping_list.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:sembast/sembast.dart' as _i3;
import 'package:sembast/src/api/transaction.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i3.Database {
  MockDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get version =>
      (super.noSuchMethod(Invocation.getter(#version), returnValue: 0) as int);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#path)),
          )
          as String);

  @override
  _i2.Future<T> transaction<T>(
    _i2.FutureOr<T> Function(_i5.Transaction)? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action]),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#transaction, [action]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#transaction, [action]),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<dynamic> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i2.Future<dynamic>.value(),
          )
          as _i2.Future<dynamic>);
}

/// A class which mocks [SembastService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSembastService extends _i1.Mock implements _i6.SembastService {
  MockSembastService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Database get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeDatabase_1(this, Invocation.getter(#database)),
          )
          as _i3.Database);

  @override
  _i2.Future<void> create(
    String? storeName,
    String? key,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [storeName, key, data]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<Map<String, dynamic>?> read(String? storeName, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [storeName, key]),
            returnValue: _i2.Future<Map<String, dynamic>?>.value(),
          )
          as _i2.Future<Map<String, dynamic>?>);

  @override
  _i2.Future<List<Map<String, dynamic>>> readAll(String? storeName) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [storeName]),
            returnValue: _i2.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i2.Future<List<Map<String, dynamic>>>);

  @override
  _i2.Future<void> update(
    String? storeName,
    String? key,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [storeName, key, data]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> delete(String? storeName, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [storeName, key]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<List<Map<String, dynamic>>> query(
    String? storeName, {
    _i3.Finder? finder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#query, [storeName], {#finder: finder}),
            returnValue: _i2.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i2.Future<List<Map<String, dynamic>>>);

  @override
  _i2.Stream<List<Map<String, dynamic>>> watchAll(String? storeName) =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, [storeName]),
            returnValue: _i2.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i2.Stream<List<Map<String, dynamic>>>);

  @override
  _i2.Stream<List<Map<String, dynamic>>> watchQuery(
    String? storeName, {
    _i3.Finder? finder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchQuery, [storeName], {#finder: finder}),
            returnValue: _i2.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i2.Stream<List<Map<String, dynamic>>>);

  @override
  _i2.Stream<Map<String, dynamic>?> watchOne(String? storeName, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#watchOne, [storeName, key]),
            returnValue: _i2.Stream<Map<String, dynamic>?>.empty(),
          )
          as _i2.Stream<Map<String, dynamic>?>);
}

/// A class which mocks [ShoppingListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockShoppingListRepository extends _i1.Mock
    implements _i7.ShoppingListRepository {
  MockShoppingListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i8.ShoppingList?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i2.Future<_i8.ShoppingList?>.value(),
          )
          as _i2.Future<_i8.ShoppingList?>);

  @override
  _i2.Future<List<_i8.ShoppingList>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i2.Future<List<_i8.ShoppingList>>.value(
              <_i8.ShoppingList>[],
            ),
          )
          as _i2.Future<List<_i8.ShoppingList>>);

  @override
  _i2.Future<void> create(_i8.ShoppingList? shoppingList) =>
      (super.noSuchMethod(
            Invocation.method(#create, [shoppingList]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> update(_i8.ShoppingList? shoppingList) =>
      (super.noSuchMethod(
            Invocation.method(#update, [shoppingList]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<List<_i8.ShoppingList>> getUserLists(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserLists, [userId]),
            returnValue: _i2.Future<List<_i8.ShoppingList>>.value(
              <_i8.ShoppingList>[],
            ),
          )
          as _i2.Future<List<_i8.ShoppingList>>);

  @override
  _i2.Future<void> addParticipant(String? listId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#addParticipant, [listId, userId]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> removeParticipant(String? listId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeParticipant, [listId, userId]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> archiveList(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#archiveList, [listId]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Stream<List<_i8.ShoppingList>> watch() =>
      (super.noSuchMethod(
            Invocation.method(#watch, []),
            returnValue: _i2.Stream<List<_i8.ShoppingList>>.empty(),
          )
          as _i2.Stream<List<_i8.ShoppingList>>);

  @override
  _i2.Stream<_i8.ShoppingList?> watchById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchById, [id]),
            returnValue: _i2.Stream<_i8.ShoppingList?>.empty(),
          )
          as _i2.Stream<_i8.ShoppingList?>);

  @override
  _i2.Stream<List<_i8.ShoppingList>> watchUserLists(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchUserLists, [userId]),
            returnValue: _i2.Stream<List<_i8.ShoppingList>>.empty(),
          )
          as _i2.Stream<List<_i8.ShoppingList>>);
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseImpl extends _i1.Mock implements _i3.Database {
  MockDatabaseImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get version =>
      (super.noSuchMethod(Invocation.getter(#version), returnValue: 0) as int);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#path)),
          )
          as String);

  @override
  _i2.Future<T> transaction<T>(
    _i2.FutureOr<T> Function(_i5.Transaction)? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action]),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#transaction, [action]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#transaction, [action]),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<dynamic> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i2.Future<dynamic>.value(),
          )
          as _i2.Future<dynamic>);
}

/// A class which mocks [SembastService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSembastServiceImpl extends _i1.Mock implements _i6.SembastService {
  MockSembastServiceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Database get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeDatabase_1(this, Invocation.getter(#database)),
          )
          as _i3.Database);

  @override
  _i2.Future<void> create(
    String? storeName,
    String? key,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [storeName, key, data]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<Map<String, dynamic>?> read(String? storeName, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [storeName, key]),
            returnValue: _i2.Future<Map<String, dynamic>?>.value(),
          )
          as _i2.Future<Map<String, dynamic>?>);

  @override
  _i2.Future<List<Map<String, dynamic>>> readAll(String? storeName) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [storeName]),
            returnValue: _i2.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i2.Future<List<Map<String, dynamic>>>);

  @override
  _i2.Future<void> update(
    String? storeName,
    String? key,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [storeName, key, data]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> delete(String? storeName, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [storeName, key]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<List<Map<String, dynamic>>> query(
    String? storeName, {
    _i3.Finder? finder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#query, [storeName], {#finder: finder}),
            returnValue: _i2.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i2.Future<List<Map<String, dynamic>>>);

  @override
  _i2.Stream<List<Map<String, dynamic>>> watchAll(String? storeName) =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, [storeName]),
            returnValue: _i2.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i2.Stream<List<Map<String, dynamic>>>);

  @override
  _i2.Stream<List<Map<String, dynamic>>> watchQuery(
    String? storeName, {
    _i3.Finder? finder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchQuery, [storeName], {#finder: finder}),
            returnValue: _i2.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i2.Stream<List<Map<String, dynamic>>>);

  @override
  _i2.Stream<Map<String, dynamic>?> watchOne(String? storeName, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#watchOne, [storeName, key]),
            returnValue: _i2.Stream<Map<String, dynamic>?>.empty(),
          )
          as _i2.Stream<Map<String, dynamic>?>);
}

/// A class which mocks [ShoppingListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockShoppingListRepositoryImpl extends _i1.Mock
    implements _i7.ShoppingListRepository {
  MockShoppingListRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i8.ShoppingList?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i2.Future<_i8.ShoppingList?>.value(),
          )
          as _i2.Future<_i8.ShoppingList?>);

  @override
  _i2.Future<List<_i8.ShoppingList>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i2.Future<List<_i8.ShoppingList>>.value(
              <_i8.ShoppingList>[],
            ),
          )
          as _i2.Future<List<_i8.ShoppingList>>);

  @override
  _i2.Future<void> create(_i8.ShoppingList? shoppingList) =>
      (super.noSuchMethod(
            Invocation.method(#create, [shoppingList]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> update(_i8.ShoppingList? shoppingList) =>
      (super.noSuchMethod(
            Invocation.method(#update, [shoppingList]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<List<_i8.ShoppingList>> getUserLists(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserLists, [userId]),
            returnValue: _i2.Future<List<_i8.ShoppingList>>.value(
              <_i8.ShoppingList>[],
            ),
          )
          as _i2.Future<List<_i8.ShoppingList>>);

  @override
  _i2.Future<void> addParticipant(String? listId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#addParticipant, [listId, userId]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> removeParticipant(String? listId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeParticipant, [listId, userId]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> archiveList(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#archiveList, [listId]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Stream<List<_i8.ShoppingList>> watch() =>
      (super.noSuchMethod(
            Invocation.method(#watch, []),
            returnValue: _i2.Stream<List<_i8.ShoppingList>>.empty(),
          )
          as _i2.Stream<List<_i8.ShoppingList>>);

  @override
  _i2.Stream<_i8.ShoppingList?> watchById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchById, [id]),
            returnValue: _i2.Stream<_i8.ShoppingList?>.empty(),
          )
          as _i2.Stream<_i8.ShoppingList?>);

  @override
  _i2.Stream<List<_i8.ShoppingList>> watchUserLists(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchUserLists, [userId]),
            returnValue: _i2.Stream<List<_i8.ShoppingList>>.empty(),
          )
          as _i2.Stream<List<_i8.ShoppingList>>);
}
